name: 'Ganotify'
description: 'Slack Notification for Github Actions'
author: 'miyabin'
inputs:
  type:
    description: 'job status (success or failure)'
    required: true
  job_name:
    description: 'job name of workflow (format: markdown)'
    required: true
  username:
    description: 'slack username'
    required: false
    default: 'Github Actions'
  icon_emoji:
    description: 'slack icon emoji'
    required: false
    default: 'github'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'white'
