name: Check Notification

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Slack Notification
        uses: miyabin66/ganotify@main
        with:
          type: ${{ job.status }}
          job_name: 'Job ${{ job.status }}'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}